version: '3'

services:
  database:
    image: mysql
    container_name: databasea
    environment:
      - MYSQL_ROOT_PASSWORD=testing
      - MYSQL_DATABASE=django
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=testing
    ports: 
      - "3306:3306"

  app:
    build: .
    container_name: djangolatse
    links:
     - database
    ports: 
      - "8000:8000"
      
    
    depends_on:
      - database

